# Generated by Django 2.2.5 on 2019-09-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_banner_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='Summary',
            field=models.TextField(default='blank', max_length=30),
            preserve_default=False,
        ),
    ]
